// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: protos/chat/v1/chat.proto

package chatv1

import (
	v1 "github.com/hardsmile98/messager/sdk/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePrivateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitiatorId   string                 `protobuf:"bytes,1,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePrivateChatRequest) Reset() {
	*x = CreatePrivateChatRequest{}
	mi := &file_protos_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePrivateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePrivateChatRequest) ProtoMessage() {}

func (x *CreatePrivateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePrivateChatRequest.ProtoReflect.Descriptor instead.
func (*CreatePrivateChatRequest) Descriptor() ([]byte, []int) {
	return file_protos_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePrivateChatRequest) GetInitiatorId() string {
	if x != nil {
		return x.InitiatorId
	}
	return ""
}

func (x *CreatePrivateChatRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type GetUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsRequest) Reset() {
	*x = GetUserChatsRequest{}
	mi := &file_protos_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsRequest) ProtoMessage() {}

func (x *GetUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_protos_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserChatsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetUserChatsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*v1.ChatInfo         `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsResponse) Reset() {
	*x = GetUserChatsResponse{}
	mi := &file_protos_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsResponse) ProtoMessage() {}

func (x *GetUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_protos_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserChatsResponse) GetChats() []*v1.ChatInfo {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *GetUserChatsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetChatInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatInfoRequest) Reset() {
	*x = GetChatInfoRequest{}
	mi := &file_protos_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatInfoRequest) ProtoMessage() {}

func (x *GetChatInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatInfoRequest.ProtoReflect.Descriptor instead.
func (*GetChatInfoRequest) Descriptor() ([]byte, []int) {
	return file_protos_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatInfoRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_protos_chat_v1_chat_proto protoreflect.FileDescriptor

const file_protos_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x19protos/chat/v1/chat.proto\x12\achat.v1\x1a\x1dprotos/common/v1/common.proto\"c\n" +
	"\x18CreatePrivateChatRequest\x12!\n" +
	"\finitiator_id\x18\x01 \x01(\tR\vinitiatorId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"j\n" +
	"\x13GetUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"i\n" +
	"\x14GetUserChatsResponse\x12)\n" +
	"\x05chats\x18\x01 \x03(\v2\x13.common.v1.ChatInfoR\x05chats\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"F\n" +
	"\x12GetChatInfoRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId2\xe4\x01\n" +
	"\vChatService\x12G\n" +
	"\x11CreatePrivateChat\x12!.chat.v1.CreatePrivateChatRequest\x1a\x0f.common.v1.Chat\x12K\n" +
	"\fGetUserChats\x12\x1c.chat.v1.GetUserChatsRequest\x1a\x1d.chat.v1.GetUserChatsResponse\x12?\n" +
	"\vGetChatInfo\x12\x1b.chat.v1.GetChatInfoRequest\x1a\x13.common.v1.ChatInfoB4Z2github.com/hardsmile98/messager/sdk/chat/v1;chatv1b\x06proto3"

var (
	file_protos_chat_v1_chat_proto_rawDescOnce sync.Once
	file_protos_chat_v1_chat_proto_rawDescData []byte
)

func file_protos_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_protos_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_protos_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_chat_v1_chat_proto_rawDesc), len(file_protos_chat_v1_chat_proto_rawDesc)))
	})
	return file_protos_chat_v1_chat_proto_rawDescData
}

var file_protos_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_chat_v1_chat_proto_goTypes = []any{
	(*CreatePrivateChatRequest)(nil), // 0: chat.v1.CreatePrivateChatRequest
	(*GetUserChatsRequest)(nil),      // 1: chat.v1.GetUserChatsRequest
	(*GetUserChatsResponse)(nil),     // 2: chat.v1.GetUserChatsResponse
	(*GetChatInfoRequest)(nil),       // 3: chat.v1.GetChatInfoRequest
	(*v1.ChatInfo)(nil),              // 4: common.v1.ChatInfo
	(*v1.Chat)(nil),                  // 5: common.v1.Chat
}
var file_protos_chat_v1_chat_proto_depIdxs = []int32{
	4, // 0: chat.v1.GetUserChatsResponse.chats:type_name -> common.v1.ChatInfo
	0, // 1: chat.v1.ChatService.CreatePrivateChat:input_type -> chat.v1.CreatePrivateChatRequest
	1, // 2: chat.v1.ChatService.GetUserChats:input_type -> chat.v1.GetUserChatsRequest
	3, // 3: chat.v1.ChatService.GetChatInfo:input_type -> chat.v1.GetChatInfoRequest
	5, // 4: chat.v1.ChatService.CreatePrivateChat:output_type -> common.v1.Chat
	2, // 5: chat.v1.ChatService.GetUserChats:output_type -> chat.v1.GetUserChatsResponse
	4, // 6: chat.v1.ChatService.GetChatInfo:output_type -> common.v1.ChatInfo
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_chat_v1_chat_proto_init() }
func file_protos_chat_v1_chat_proto_init() {
	if File_protos_chat_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_chat_v1_chat_proto_rawDesc), len(file_protos_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_protos_chat_v1_chat_proto_depIdxs,
		MessageInfos:      file_protos_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_protos_chat_v1_chat_proto = out.File
	file_protos_chat_v1_chat_proto_goTypes = nil
	file_protos_chat_v1_chat_proto_depIdxs = nil
}
