// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: protos/presence/v1/presence.proto

package presencev1

import (
	v1 "common/pkg/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_protos_presence_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_presence_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_protos_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *GetPresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceRequest) Reset() {
	*x = SetPresenceRequest{}
	mi := &file_protos_presence_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceRequest) ProtoMessage() {}

func (x *SetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_presence_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceRequest.ProtoReflect.Descriptor instead.
func (*SetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_protos_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *SetPresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPresenceRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *SetPresenceRequest) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_protos_presence_v1_presence_proto protoreflect.FileDescriptor

const file_protos_presence_v1_presence_proto_rawDesc = "" +
	"\n" +
	"!protos/presence/v1/presence.proto\x12\vpresence.v1\x1a\x1dprotos/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x12GetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x12SetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x127\n" +
	"\tlast_seen\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen2\x9b\x01\n" +
	"\x0fPresenceService\x12C\n" +
	"\vGetPresence\x12\x1f.presence.v1.GetPresenceRequest\x1a\x13.common.v1.Presence\x12C\n" +
	"\vSetPresence\x12\x1f.presence.v1.SetPresenceRequest\x1a\x13.common.v1.PresenceB%Z#presence/pkg/presence/v1;presencev1b\x06proto3"

var (
	file_protos_presence_v1_presence_proto_rawDescOnce sync.Once
	file_protos_presence_v1_presence_proto_rawDescData []byte
)

func file_protos_presence_v1_presence_proto_rawDescGZIP() []byte {
	file_protos_presence_v1_presence_proto_rawDescOnce.Do(func() {
		file_protos_presence_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_presence_v1_presence_proto_rawDesc), len(file_protos_presence_v1_presence_proto_rawDesc)))
	})
	return file_protos_presence_v1_presence_proto_rawDescData
}

var file_protos_presence_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_presence_v1_presence_proto_goTypes = []any{
	(*GetPresenceRequest)(nil),    // 0: presence.v1.GetPresenceRequest
	(*SetPresenceRequest)(nil),    // 1: presence.v1.SetPresenceRequest
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*v1.Presence)(nil),           // 3: common.v1.Presence
}
var file_protos_presence_v1_presence_proto_depIdxs = []int32{
	2, // 0: presence.v1.SetPresenceRequest.last_seen:type_name -> google.protobuf.Timestamp
	0, // 1: presence.v1.PresenceService.GetPresence:input_type -> presence.v1.GetPresenceRequest
	1, // 2: presence.v1.PresenceService.SetPresence:input_type -> presence.v1.SetPresenceRequest
	3, // 3: presence.v1.PresenceService.GetPresence:output_type -> common.v1.Presence
	3, // 4: presence.v1.PresenceService.SetPresence:output_type -> common.v1.Presence
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_presence_v1_presence_proto_init() }
func file_protos_presence_v1_presence_proto_init() {
	if File_protos_presence_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_presence_v1_presence_proto_rawDesc), len(file_protos_presence_v1_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_presence_v1_presence_proto_goTypes,
		DependencyIndexes: file_protos_presence_v1_presence_proto_depIdxs,
		MessageInfos:      file_protos_presence_v1_presence_proto_msgTypes,
	}.Build()
	File_protos_presence_v1_presence_proto = out.File
	file_protos_presence_v1_presence_proto_goTypes = nil
	file_protos_presence_v1_presence_proto_depIdxs = nil
}
